version: '3.1'
services:
  mysqlsrv:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: "projetoDb"
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  adminer:
    image: adminer
    restart: always
    ports:
      -  8080:8080
    networks:
      - mysql-network
      
networks:
  mysql-network:
    driver: bridge